config/routes.rb
Rails.application.routes.draw do

  get 'friends/search'

  get 'friends/index'

  get 'notes/search'
  get 'tips/index'
  get 'top/index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  resources :notes
  get 'notes/share/:id' => 'notes#share'
  get 'share' => 'notes#share_update'

  root 'top#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
	has_many :shares
	has_many :users, :through => :shares
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:share, :show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    # @notes = Note.order("updated_at DESC")
    # @notes = Note.all.reverse_order
    # @notes = Note.all
    @notes = Note.where( 'user_id' => current_user.id ).reverse_order

    @shared_notes = User.find(current_user.id).notes
  end


  # GET /notes/1
  # GET /notes/1.json
  def show
    gon.text_list = @note.contents
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  def share
    @friends = User.find(current_user.id).friends
  end

  def share_update
    params[:user_id].each do |shared_user_id|
      # if Share.where(note_id: params[:note_id]).where(user_id: shared_user_id) == nil
       Share.create(:note_id => params[:note_id], :user_id => shared_user_id)
      # end
    end 
    @note = Note.find(params[:id])
    @friends = User.find(current_user.id).friends
    render "share"
  end

  def search
    # @notes = Note.scoped
    @notes = Note.where(['name LIKE ? or contents LIKE ?', 
      "%#{params[:search]}%","%#{params[:search]}%"]).reverse_order if
      params[:search].present?
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :contents)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = "edit-form">
  <div class="edit-name-form">
    <!-- <%= f.label :name %><br> -->
    <%= f.text_field :name, class: "edit-note-title", placeholder:"title" %>
  </div>
  <div class="edit-text-form">
    <!-- <%= f.label :contents %><br> -->
    <%= f.text_area :contents, class: "edit-note-text", size: "60x20" %>
    <div id="result"></div>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
  </div>  

<!--   <div class = "from_edit-to_show">
    <% if controller.controller_name == "notes" && controller.action_name == "edit" %>
      <%= link_to 'Show', @note, class:"link-to-show" %>
    <% end %>
  </div> -->

  <div class="link-button">
    <%= f.submit  %>
    <div class="link-to-note-btn">
      <%= link_to 'Back', notes_path, class:"back-btn" %>
    </div>
  </div>

</div>
<% end %>

app/views/notes/edit.html.erb
  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>




	<div class = "main-column">
		<div class = "main-position">
			<%= render 'form' %>
		</div>
	</div>

 	<div id="footer">
		<p><small>
			Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
	</div>
	<!-- </body> -->

<!-- </html> -->

app/views/notes/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>

<!-- 
  <div class = "main-column">
    <div class = "main-position">
      <div class="notelist-column">
      </div>
    </div>
  </div>
 -->

<table class="noteList">
  <thead>
    <tr>
      <th>Name</th>
      <th>Updated_at</th>
      <th>Author</th>
      <th class="button-rows"></th>
      <th class="button-rows"></th>
      <th class="button-rows"></th>
      <!-- <th class="button-rows"></th> -->
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td class="noteRows noteRows-title"><%= note.name %></td>
        <td class="noteRows noteRows-update"><%= note.updated_at %></td>
        <td class="noteRows noteRows-author"><%= note.user_id %></td>
        <td class="noteRows button-rows"><%= link_to 'Show', note, class:"notes-show-btn" %> </td>
        <td class="noteRows button-rows"><%= link_to 'Edit', edit_note_path(note) %></td>
        <td class="noteRows button-rows"><%= link_to 'Destroy', note, method: :delete, data: { confirm: '選択したノートを削除します．よろしいですか？' } %></td>
        <!-- <td class="noteRows button-rows">share</td> -->
        <!-- ここに share のボタンを追加したい． -->
      </tr>
    <% end %>
    <% @shared_notes.each do |note| %>
      <tr>
        <td class="noteRows noteRows-title"><%= note.name %></td>
        <td class="noteRows noteRows-update"><%= note.updated_at %></td>
        <td class="noteRows noteRows-author"><%= note.user_id %></td>
        <td class="noteRows button-rows"><%= link_to 'Show', note, class:"notes-show-btn" %> </td>
        <td class="noteRows button-rows"></td>
        <td class="noteRows button-rows"><%= link_to 'Destroy', note, method: :delete, data: { confirm: '選択したノートの共有を削除します．よろしいですか？' } %></td>
        <!-- <td class="noteRows button-rows">share</td> -->
        <!-- ここに share のボタンを追加したい． -->
      </tr>
    <% end %>
  </tbody>
</table>


  <div id="footer">
    <p><small>
      Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
  </div>

app/views/notes/new.html.erb
	<%= javascript_include_tag "application" %>

  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
  

	<div class = "main-column">
		<div class = "main-position">
			<!-- <form> -->
			<%= render 'form' %>
			<!-- <%= link_to 'Back', notes_path %> -->
			<!-- <textarea rows="20" class="edit-note-text" cols="60"></textarea> -->
			<!-- </form> -->

		</div>
	</div>

 	<div id="footer">
		<p><small>
			Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
	</div>

app/views/notes/search.html.erb
  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>


  <div class="note-search-form">
  	<%= form_tag notes_search_path, :method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
  	<p>
    <%= text_field_tag :search, params[:search], class:"note-search-field", placeholder:"ノートを検索" %>
    <%= submit_tag "Search", class:"note-search-btn", :name => nil %>
  	</p>
	<% end %>
  </div>

  <div class = "note-search-list">
	<% if params[:search].present? %>
	  <table class="noteList">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Updated_at</th>
		      <th class="button-rows"></th>
		      <th class="button-rows"></th>
		      <th class="button-rows"></th>
		      <th class="button-rows"></th>
		      <!-- <th colspan="3"></th> -->
		    </tr>
		  </thead>

		  <tbody>
		    <% @notes.each do |note| %>
		      <tr>
		        <td class="noteRows noteRows-title"><%= note.name %></td>
		        <td class="noteRows"><%= note.updated_at %></td>
		        <td class="noteRows button-rows"><%= link_to 'Show', note, class:"notes-show-btn" %> </td>
		        <td class="noteRows button-rows"><%= link_to 'Edit', edit_note_path(note) %></td>
		        <td class="noteRows button-rows"><%= link_to 'Destroy', note, method: :delete, data: { confirm: '選択したノートを削除します．よろしいですか？' } %></td>
		        <td class="noteRows button-rows">share</td>
		        <!-- ここに share のボタンを追加したい． -->
		      </tr>
		    <% end %>
		  </tbody>
		</table>
  	<% else %>
    	<!-- 何も表示しない -->
  	<% end %>
  </div>

  <div id="footer">
    <p><small>
      Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
  </div>

app/views/notes/share.html.erb
  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>


  
  <!-- <p id="notice"><%= notice %></p> -->

  <div class="note-search-form">
    <%= form_tag('/share', :method => :get) do %>
    <%= hidden_field_tag "id", @note.id %>
    <%= hidden_field_tag "note_id", @note.id %>
      <% @friends.each do |friend|%>
        <%= check_box_tag 'user_id[]',friend.id, false, id: friend.user_name%>
        <%= label_tag friend.user_name, friend.user_name %>
      <% end %>
    <p class = "friends-sentence">この「<%= @note.name%>」を共有するフレンドの名前を入力してください．</p>
  </div>

  <div class="share-submit-btn">
    <%= submit_tag "共有する", class:"share-btn", :name => nil %>
    <% end %>
  </div>
  </div>



 	<div id="footer">
		<p><small>
			Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
	</div>

app/views/notes/show.html.erb
  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>



  <!-- <p id="notice"><%= notice %></p> -->

  <div class = "show-column">
		<div class = "note-name">
		  	<h2><%= @note.name %></h2>
        <% if @note.user_id == current_user.id%>
        <%= link_to "share", {action: 'share', id: @note.id} , class:"share_btn" %>
        <% end %>
		</div>

		<div id="viewer"></div>

		<div class = "show-list-btn">
			<%= link_to 'Edit', edit_note_path(note) , class:"show-to-btn"%>
			<%= link_to 'Back', notes_path, class:"show-to-btn" %>
		</div>
	</div>
    
    <%= form_for(@note) do |f| %>
    <div class = "edit-form" style="display:none">
      <div class="edit-text-form">
      <%= f.text_area :contents, class: "edit-note-text", size: "60x20" %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
      </div>
    </div>  
    <% end %>

 	<div id="footer">
		<p><small>
			Copyright&copy; 2015 @Daiki Ito, Yuji Koketsu All Rights Reserved.</small></p>
	</div>