config/routes.rb
Rails.application.routes.draw do

  get 'friends/search'

  get 'friends/index'

  get 'notes/search'
  get 'tips/index'
  get 'top/index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  resources :notes
  get 'notes/share/:id' => 'notes#share'
  get 'share' => 'notes#share_update'

  root 'top#index'

end

app/models/share.rb
class Share < ActiveRecord::Base
	belongs_to :user
	belongs_to :note
end

app/helpers/share_helper.rb
module ShareHelper
end

app/views/share/index.html.erb
  <div class = "head-list-column">
    <div class = "logomark-a">
      <h2>~ E n o t i n g ~</h2>
      <!-- <img src="image/logo.png" alt="Enoting ロゴ" width="140" height="100"> -->
      <!-- ロゴ思案中 -->
    </div>

    <div class= "subcolumn-bar">
      <ul class = "dropmenu">
        <li id="note-source"><a>ノート</a>
          <ul>
            <li><%= link_to 'ノート一覧', notes_path %></li>
            <li><%= link_to 'ノート検索', notes_search_path %></li>
            <li><%= link_to '新しくノートを作成', new_note_path %></li>
          </ul>
        </li>
        <li><a>フレンド</a>
          <ul>
            <li><%= link_to 'フレンド一覧', friends_index_path %></li>
            <li><%= link_to 'フレンド検索', friends_search_path %></li>
          </ul>
        </li>
        <li><a>プロフィール</a>
          <ul>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          </ul>
        </li>
        <li><a>tips</a>
          <ul>
            <li><%= link_to 'Markdownとは？', tips_index_path %></li>
          </ul>
        </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>

  <div class = "my-friend-list">
    <h2>このノートを共有したい友達を選んでください．</h2>
    <%= check_box_tag(:user_name, "name") %>
    <%= check_box_tag(:user_name, "name") %>
    <%= check_box_tag(:user_name, "name") %>
    <% @user.friends.uniq.each do |friend| %>
    <p><%= check_box_tag(:user_name, "name") %><%= friend.user_name %></p>
    <%= Share.create(:note_id => note.id, :user_id => friend.id) %>
    <% end %>
  </div>

  <div class="share-submit-btn">
    <%= form_tag share_index_path, :method => 'get' do %>
    <%= submit_tag "共有する", class:"share-btn", :name => nil %>
    <% end %>
  </div>